### ISSUE TITLE
Select text

### ISSUE THREAD

**Issue by Valdnet** [ManeraKai/simplytranslate_mobile#61]
Steps:

1. Enter a very long text.
2. Select all text.

The selection menu with the "tear" is visible outside the text window:

![obraz](https://user-images.githubusercontent.com/47037905/134041567-843e608e-0163-4013-865a-3d17bff0af30.png)

**Comment by ManeraKai** [comment]
This is fixed.

**Comment by Valdnet** [comment]
Request to reopen issue.
_As an issue author, I still cannot open closed issues._

Steps:

1. Enter long text.
2. Select the text in its entirety.

The selected long text also appears at the top of the application.

![obraz](https://user-images.githubusercontent.com/47037905/134326186-7966537a-fc60-437d-8968-1f59c2d12f25.png)

- The action selection window should appear either in the edit window or close to the edit window.
- When scrolling through long text, the selection window should disappear and reappear near the window when you release your finger.

**Comment by ManeraKai** [comment]
> the selection window should disappear and reappear 

I noticed that, but I don't think it's a bug. I think it's how text toolbar generally works in android and flutter. It goes up to inform you where the real text selection is instead of just sticking to the border of the text field and misleading about where did you start your selection. The tear button is removed though as it won't be useful because you can't tweak selection without seeing the text.

**Comment by Valdnet** [comment]
> I noticed that, but I don't think it's a bug. I think it's how text toolbar generally works in android and flutter.

The text toolbar works as follows:

1. Appears with selected text.
2. If the selected text is long and does not fit in the text window, it appears underneath the window so as not to obscure the selected text.
3. If you move your finger over the text, the text toolbar disappears as you move it and reappears in the same place.
4. In your application, the toolbar moves with the text, which causes a strange visual effect.

**Comment by ManeraKai** [comment]
Here I've added a container with fixed hide to limit the size of the TextField. It doesn't obey:
![image](https://user-images.githubusercontent.com/40805353/134342274-991f19dc-1fed-4abf-a24c-12cb965a794e.png)

**Comment by Valdnet** [comment]
In my opinion it should appear at the bottom of the text window and a little closer to the window.

**Comment by Valdnet** [comment]
A good idea, but it won't work for a single word. The bar will be too high from the selected text.

![obraz](https://user-images.githubusercontent.com/47037905/134345762-93ff3d4e-ff02-476a-8c43-f25fc1ca3c7c.png)

To select a **single** word:

The toolbar visibility coordinates should be set so that it should appear close to the selected single text, but if, after scrolling the text, when the selection hides beyond the boundaries of the editing window, the text toolbar should stay close to the border of the editing window.

- Selected text at the top of the window:

![obraz](https://user-images.githubusercontent.com/47037905/134348992-6a682055-4f2f-4a31-8962-a4928b6e752f.png)

- Selected text at the top of the window after scrolling:

![obraz](https://user-images.githubusercontent.com/47037905/134348892-13e636ea-7ed2-4446-86f7-e27ac2bc2bc6.png)

- Selected text at the bottom of the window:

![obraz](https://user-images.githubusercontent.com/47037905/134348734-5707ce63-052f-4335-b143-d81cf2302fc5.png)

- Selected text at the bottom of the window after scrolling:

![obraz](https://user-images.githubusercontent.com/47037905/134348634-005d4591-4355-4262-8a71-54bb058934c8.png)

**Comment by ManeraKai** [comment]
>A good idea, but it won't work for a single word. The bar will be too high from the selected text.

No, I wrote that comment to show you that this is how Flutter's TextField works by default. Try to scroll more till the toolbar reach the top of the screen. It'll snap back down and slowly go up as you scroll more. It's really designed that way.

**Comment by Valdnet** [comment]
It can't stay that way because it looks strange. I tested another application and the text editing bar works as expected.

Maybe you need to give the text edit bar a condition:
e.g.:
Display the text editing bar from the selected text, e.g. 50px, but not higher (lower) than e.g. 100px from the window border.

**Comment by Valdnet** [comment]
This problem is bothering me. This solution for the application is still missing.
After the tests, it turns out that the application takes the entire application field as text editing (marked in the screenshot).

![obraz](https://user-images.githubusercontent.com/47037905/134796183-fb030f1d-b944-4047-8e38-6c9c47d8c465.png)

![obraz](https://user-images.githubusercontent.com/47037905/134796332-21ab4bd2-c383-411f-ab77-c5e3039c2296.png)

Is it possible to set only this field?

![obraz](https://user-images.githubusercontent.com/47037905/134796354-90a020ce-3bb3-4f45-bbce-93e85ae04876.png)

When you move the application window while editing text, the toolbar goes completely outside the application boundaries.

![obraz](https://user-images.githubusercontent.com/47037905/134796426-5827a68f-10a0-40bf-8276-da554a2a5bbd.png)

@ManeraKai Consider this issue again before releasing a new version 😉.

**Comment by ManeraKai** [comment]
https://user-images.githubusercontent.com/40805353/134805125-46dd7692-5061-47dd-94c8-61166133ac5f.mp4

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1275126662

**Comment by Valdnet** [comment]
Now is good.
Just to scroll the entire application window, hide the text editing tools under the top application banner.

Steps:

1. Enter your text.
2. Highlight the text.
3. Move the entire application window up.

![obraz](https://user-images.githubusercontent.com/47037905/134807947-f430ae09-b2f1-4c67-94a4-58edd4977a21.png)

Maybe the solution would be to hide the text editing tool under the app banner to hide under it.

Example:

![obraz](https://user-images.githubusercontent.com/47037905/134808074-2667ef59-3cad-43c3-a000-d34acd40a0fc.png)

**Comment by Valdnet** [comment]
And the font color should be changed from black to white.

**Comment by ManeraKai** [comment]
It will be buggy. It should be added to the translated text widget too. Orientation and scrolling will break the fixed position numbers. I'm not confident to put it in this release at least.

**Comment by Valdnet** [comment]
Well. Just yet change the font color for the text editing tool to white in light theme.

**Comment by ManeraKai** [comment]
Changed it.

**Comment by Valdnet** [comment]
I am asking for a new test version and I am doing a general test of the application :grin:.

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1275254538

**Comment by Valdnet** [comment]
I am asking for a new version of the application. The current one does not contain @Aga-C changes.

**Comment by ManeraKai** [comment]
No problem: https://github.com/ManeraKai/simplytranslate-flutter-client/actions/runs/1275317938

**Comment by Valdnet** [comment]
I am in favor of blocking application scrolling. When typing a translation, it is not needed. This will eliminate the problem with text editing tools leaving the application window.

**Comment by ManeraKai** [comment]
If you eliminate it, it will give an overflow problem.

**Comment by Valdnet** [comment]
I mean scrolling the entire application. So good 😉.

Scrolling is needed when the smartphone is in a horizontal position.

**Comment by ManeraKai** [comment]
Scrolling is also needed for portrait, not every phone has a 18:9 display.

**Comment by Valdnet** [comment]
It doesn't look good in this version 😬. Icons and selection boxes extend beyond the application.

**Comment by Valdnet** [comment]
The text window should be left unchanged (it must be fixed as it is in version 1.1.2). You only need to think over the text edit bar to make it display properly close to the window. As is the case with other text editing applications.

**Comment by Valdnet** [comment]
Works fine, but I am still in favor of keeping the window fixed size. After a very long text is translated, it gets uninteresting. Extends the application window very much. The user doesn't know something is really going on. The translated text is not visible immediately.

I am in favor of scrolling through the text and looking for a different solution.

**Comment by ManeraKai** [comment]
> I don't see much of it. I propose a different solution. See other apps how it works.

That is how Google Translate works

> When selecting text, the text editing bar disappears momentarily while you move the text and reappears in the same position.

Do they have fixed TextField heights? I didn't find any that do that myself.

**Comment by Valdnet** [comment]
Maybe this will tell you something: [GitLab TextField](https://gitlab.com/search?search=TextField&group_id=&project_id=13268901&scope=&search_code=true&snippets=false&repository_ref=master&nav_source=navbar).

**Comment by ManeraKai** [comment]
https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1342020170

**Comment by ManeraKai** [comment]
Where?

https://user-images.githubusercontent.com/40805353/137361248-3dfc2140-5f59-441d-bc5a-6d5436b2a9be.mp4

**Comment by ManeraKai** [comment]
Nothing:

https://user-images.githubusercontent.com/40805353/137362748-31e8a931-0812-4e88-95c5-c319cdea6ec5.mp4

**Comment by Valdnet** [comment]
When you start the application for the **first** time and paste and select text.

You have an **active bar** when you start it for the first time.

Also remove this shadow on the keyboard. Does not match the application and it interferes with horizontal editing of the window.

![obraz](https://user-images.githubusercontent.com/47037905/137363136-217f87db-d6fc-4270-90df-5c8a9c23e18c.png)

**Comment by Valdnet** [comment]
Not. Before it was fine.

**Comment by ManeraKai** [comment]
Tried to reproduce it on my device, no hope.

We'll try somethings, does this work?: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1345019159

**Comment by Valdnet** [comment]
Yes. It also happens when I use the normal text editing bar in this application (version 1.1.2).

**Comment by Valdnet** [comment]
Still the same bugs 😬.

I have checked in version 1.1.1, this problem is also there.

**Comment by Valdnet** [comment]
I checked on another application. The solution to this is that when you scroll the text in the window, the text cursor hovers on the given line of text. Still visible in the text window.

**Comment by Valdnet** [comment]
So far I can't confirm with another user.

The best solution is to have the cursor positioned automatically in a visible place in the window when the text is scrolled. This is also how other applications are resolved.

**Comment by ManeraKai** [comment]
> And did you check with the cursor position:
> 
> > I've found that this problem only happens when the text cursor is outside the edit window while selecting.
> > If the cursor is in the field of view of the window, the text selection is correct.

ooh yeah! the key was found. Apparently, you select by long pressing instead of tap tapping:

https://user-images.githubusercontent.com/40805353/137475467-f2cfecd9-570e-41ab-87a7-343b4e652d2d.mp4

**Comment by ManeraKai** [comment]
To be in context. I can detect user scrolling, but I'm now trying to calculate the cursor's position. You should take in mind if there is a line break in the text, a word overflow that created a new line. Because the cursors position is based on just letters and not lines.

**Comment by Valdnet** [comment]
As we now know what is the cause, you may need to find the cause of it. Then you don't have to implement all of this :wink:.

**Comment by Valdnet** [comment]
You could say so. But doesn't that trigger some function that sets the text to the position of the cursor?

**Comment by ManeraKai** [comment]
I mean it's the cursor, of course text will be written from that point.

**Comment by Valdnet** [comment]
No change. The behavior is still the same.

**Comment by ManeraKai** [comment]
The paste button escape correction will work here: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1348736133

**Comment by ManeraKai** [comment]
?

**Comment by Valdnet** [comment]
1. If you paste text from the text edit bar:

![obraz](https://user-images.githubusercontent.com/47037905/137588834-86416c9b-bd99-4279-a45f-7764e5bdb22b.png)

then there is also a text selection problem. The text automatically scrolls.

2. The problem with automatically scrolling text while selecting also appears when you paste or type more than 9870 characters.

**Comment by ManeraKai** [comment]
Hopefully: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/1349216426

**Comment by ManeraKai** [comment]
> After exceeding **32399** characters, the problem also arises when selecting the text.

bruh

**Comment by ManeraKai** [comment]
btw, why should we limit the character limit to below 99999 if it won't affect anything? I can just stop the character counting from counting more rather than editing and changing the text.

**Comment by ManeraKai** [comment]
> I think you got me wrong.

> Text must be supported up to 99999.

I understood, but because it's getting too complicated and any bug can rise as we are now playing with the text selection values  from multiple parties.

**Comment by Valdnet** [comment]
So, the application is supposed to work properly up to a certain number of characters, and then it can automatically scroll the text uncontrollably by the user?

**Comment by ManeraKai** [comment]
No, I'm trying to find and fix that bug, but just for simplicity of code and preventing future bugs I'll remove the force limiter as there is no need to it.

**Comment by Valdnet** [comment]
Well. So I will wait for the corrected version 😉.

**Comment by Valdnet** [comment]
It doesn't always work properly. Sometimes it allows more characters to be pasted and works right, sometimes it only allows fewer characters.

**Comment by ManeraKai** [comment]
It's a sneaky workaround, not a real solution. The real solution is centering the cursor. Waiting for an answer: https://stackoverflow.com/questions/69587533/center-cursor-in-textfield-flutter

**Comment by ManeraKai** [comment]
I'll leave this issue then for another time. At least we minimized the problem for now.

**Comment by Valdnet** [comment]
The correct behavior of the application when editing the text window is in the project [FastHub](https://github.com/k0shk0sh/FastHub).
When scrolling, the edit bar hides and reappears next to the text window, and the cursor is always visible in the text window when the text is scrolled.

Maybe it will help you 😉.

**Comment by Valdnet** [comment]
Is it possible to count the number of lines of text, then count how many lines are scrolled forwards or backwards and calculate on which line the cursor should appear?

**Comment by ManeraKai** [comment]
@Valdnet is the problem solved in the latest beta version?! https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2045778266

**Comment by ManeraKai** [comment]
Here is it disabled: https://github.com/ManeraKai/simplytranslate_mobile/actions/runs/2047328527

**Comment by Valdnet** [comment]
@ManeraKai Have the changes been made or have you opted out of them?

**Comment by ManeraKai** [comment]
no I've disabled the `selection tool bar`. It's now vanilla input you can say.

**Comment by Valdnet** [comment]
In my opinion, it works incorrectly. It leaves the main application window.

**Comment by ManeraKai** [comment]
It just becomes hidden when the cursor leaves the screen right?
